CREATE TABLE IF NOT EXISTS BLACKLISTED_CHAPTER (
    ID             varchar    NOT NULL PRIMARY KEY,
    SERIES_ID      varchar    NOT NULL,
    CHAPTER_URL    varchar(2048) NOT NULL,
    CHAPTER_NUMBER varchar(50),
    CHAPTER_TITLE  varchar(512),
    CREATED_DATE   datetime   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (SERIES_ID) REFERENCES SERIES(ID) ON DELETE CASCADE
);
CREATE UNIQUE INDEX idx_blacklisted_chapter_url ON BLACKLISTED_CHAPTER (CHAPTER_URL);
CREATE INDEX idx_blacklisted_chapter_series ON BLACKLISTED_CHAPTER (SERIES_ID);
