CREATE TABLE IF NOT EXISTS IGNORED_OVERSIZED_PAGE (
    BOOK_ID      varchar NOT NULL,
    PAGE_NUMBER  int     NOT NULL,
    MODE         varchar(10) NOT NULL,
    CREATED_DATE datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (BOOK_ID, PAGE_NUMBER, MODE),
    FOREIGN KEY (BOOK_ID) REFERENCES BOOK(ID) ON DELETE CASCADE
);
CREATE INDEX idx_ignored_oversized_page_book ON IGNORED_OVERSIZED_PAGE (BOOK_ID);
CREATE INDEX idx_ignored_oversized_page_mode ON IGNORED_OVERSIZED_PAGE (MODE);
